### ISSUE TITLE
request shallow comparison with then() should compare the original mapping? 

### ISSUE THREAD

**Issue by nfcampos** [heroku/react-refetch#102]
This is similar to #53 but not exactly the same because I think this `parent` comparison should be true also when you don't provide `comparison`
eg.
```js
@connect(({ foo }) => ({
  testFetch: {
    url: `/resource/${foo}`,
    then(value) {
      return { value }
    }
  }
}))
class WithProps extends Component {
  ...
}
```
currently the comparison of requests compares `{ value }` that resulted out of the `then` with `{ url: `/resource/${foo}` }` of then new original request, this makes the comparison logic all but useless when `then` is used. It seems to me that the expected behaviour would be for the new original mapping to be compared with the previous original mapping (not the one resulting from then). Do you agree @ryanbrainard?

**Comment by ryanbrainard** [comment]
Good call. What if we just implicitly set `force: true` on `then` and `catch`? That should allow us to simplify/remove all that `parent` business. (I feel like there was a good reason I didn't do this before, but can't recall now.)

**Comment by nfcampos** [comment]
hmm... but if we set `force: true` on `then` and `catch` doesn't that mean that any request with a `then` will be refetched every time `mapPropsToRequestsToProps` is called? That sounds wasteful, and surprising to the user, no?

**Comment by ryanbrainard** [comment]
mapPropsToRequestsToProps should recalculate the mappings and set force to
false (unless actually true) again. I'll need to confirm and test things
out, but I think it should work.

**Comment by tomat** [comment]
Just stumbled on this when building [react-reflorp](https://github.com/tomat/react-reflorp), resorted to explicitly setting `comparison` in the original mapping, and then the same `comparison` and `force: true` in `then`, but I would expect a more logical default behaviour. Took some debugging to figure out why this was happening. Maybe store the last non-identity-request mapping on each key and compare to that unless comparison is set?
