### ISSUE TITLE
Response headers are getting lost

### ISSUE THREAD

**Issue by volkanunsal** [heroku/react-refetch#116]
When you consume the response body via `response.json()` the response headers are no longer accessible. The `Headers` object in `meta` property appears empty. The default implementation of `handleResponse` doesn't make any provisions for preserving headers for later use. How might we roll out a response handler to ensure the headers are still accessible afterwards?

**Comment by nfcampos** [comment]
reading the `Response` body via `response.json()` only consumes the body not the headers. The headers are made available at `meta.response.headers`. Can you provide more detail of your situation in which the headers are not available?

**Comment by volkanunsal** [comment]
@nfcampos That's weird. That's not what I'm seeing. The `meta` object of a fulfilled `PromiseState` appears to be empty for me. My response is also being post-processed in a promise, though, so that might be the issue. 

```javascript
projectSearch: {
      url: `/api/search${queryString}`,
      comparison: queryString,
      then: (results) => {
        return {
          value: normalizeProjects(results)
        }
      }
    },
```

I can't get the returned value from a `then` method to include a non-empty `meta` property. If I had access to the original PromiseState in that block, rather than only the `json()` output, that would solve the problem for me.

**Comment by nfcampos** [comment]
Ah, I see. That's replacing the whole PromiseState with one that has just `value` and doesn't have `meta` anymore. I believe `meta` is available as the 2nd arg to the `then` handler.

**Comment by volkanunsal** [comment]
Problem solved. 👍

**Comment by vrinceanuv** [comment]
I have the same issue on cors request, response headers are empty. I get an empty object...
