### ISSUE TITLE
React-Native TransformError - Preset "es2015-loose"

### ISSUE THREAD

**Issue by hirviid** [heroku/react-refetch#131]
Importing react-refetch in a react native projects breaks with following error:

`TransformError: /Users/david/Documents/Projects/marathon/node_modules/react-refetch/lib/index.js: Couldn't find preset "es2015-loose" relative to directory "<path>/node_modules/react-refetch"`

Looks like the same problem as described in redux-devtools: https://github.com/gaearon/redux-devtools-log-monitor/issues/34

They fixed this by excluding .babelrc from npm package. 

I tested this solution by removing .babelrc from the react-refetch directory in my node_modules. Now the projects runs perfectly with react-refetch. Is it possible to exclude .babelrc from the npm package?

**Comment by ryanbrainard** [comment]
See #132

**Comment by ryanbrainard** [comment]
Fixed by https://github.com/heroku/react-refetch/pull/133
