### ISSUE TITLE
Lazy loading does not work

### ISSUE THREAD

**Issue by msaron** [heroku/react-refetch#135]
Lazy loading is not working. I have the following code and am using React 15.2 and react-refetch 1.0.0-beta.8. 

        // country-list.jsx
	class CountryList extends Component {
	  componentDidMount() {
		this.props.loadData()
	  }

	  render() {
		const { countriesFetch } = this.props;

		if (countriesFetch.pending) {
		  return <div>Loading data...</div>
		} else if (countriesFetch.rejected) {
		  return <div>Error: {countriesFetch.reason}</div>
		} else if (countriesFetch.fulfilled) {
		  return (
		    <div>
		      <BsGrid data={countriesFetch.value.results} showSelect={true} showEdit={true} edit={this.handleEditClick} />
		    </div>
		  );
		}
	  }
	}

	export default connect(props => ({
	  loadData: () => ({countriesFetch: '/world/country'})  // does NOT work.
	  // countriesFetch: '/world/country'  // only this one works.
	}))(CountryList)

I get an error saying 
`country-list.jsx:22Uncaught TypeError: Cannot read property 'pending' of undefined`

**Comment by nfcampos** [comment]
this happens because the first time `render` is called componentDidMount hasn't been called yet, so countriesFetch isn't defined yet. makes sense?

**Comment by msaron** [comment]
Yes. Thank you!!!
