### ISSUE TITLE
Undefined response on POST requests

### ISSUE THREAD

**Issue by skDn** [heroku/react-refetch#136]
I don't get any response object after performing a POST. 

> export default connect(props => ({
    postTask: task => ({
        postTaskResponse: {
            url: `/api/task`,
            method: 'POST',
            body: JSON.stringify(task)
        }
    })
}))(PostTaskForm)

PostTask works fine but postTaskResponse remains undefined after calling postTask. I have tried accessing it like this.props.postTaskResponse or just postTaskResponse as it is in the example in the documentation but in both cases it is undefined. The server returns a JSON on POST requests.

> postTask: function () {
        this.props.postTask(task);
        console.log(this.state.postTaskResponse); //  gives undefined
        console.log(this.postTaskResponse); // gives undefined
        console.log(postTaskResponse); // gives postTaskResponse is not defined
        this.props.close();
    },

I'm using:

>     "react": "^15.2.1",
    "react-dom": "^15.2.1",
    "react-refetch": "^1.0.0-beta.8",

**Comment by ryanbrainard** [comment]
The response will not be immediately available because it is async. Instead, you need to do your logging inside `render()` and it should be populated on the next render that is triggered. Note, it should be `console.log(this.props.postTaskResponse)`.

**Comment by ryanbrainard** [comment]
Closing this unless it is still an issue.
