### ISSUE TITLE
fulfilled for 404 of http-server

### ISSUE THREAD

**Issue by stupidisum** [heroku/react-refetch#137]
`http-server` served a blank 404 error for unimplemented api.
`re-fetch` tried to parse it and got fulfilled and `fetch.value` is `null`

**Comment by ryanbrainard** [comment]
I just did a quick unit test for this, but it's working for me. Can you provide details about the exact response headers and body, and also what lib you are using for `fetch`?

**Comment by stupidisum** [comment]
Request URL:http://127.0.0.1:8081/api/sensors
Request Headers
Provisional headers are shown
accept:application/json
content-type:application/json
Referer:http://127.0.0.1:8081/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36

**Comment by stupidisum** [comment]
chrome browser fetch

**Comment by stupidisum** [comment]
```js

  const ComponentWithSensors = ({ sensorsFetch, ...rest }) => {
    if (sensorsFetch.pending) {
      console.info('pending', sensorsFetch);
      return <Component sensors={defaultSensors} />;
    } else if (sensorsFetch.rejected) {
      console.info('rejected', sensorsFetch);
      return <Component sensors={defaultSensors} />;
    } else if (sensorsFetch.fulfilled) {
      console.info('fulfilled', sensorsFetch);
      return <Component {...rest} sensors={sensorsFetch.value || defaultSensors} />;
    }
    return <Component sensors={defaultSensors} />;
  };
```

**Comment by stupidisum** [comment]
Sorry, I can't reproduce it, either. But now I have another serious problem #138.
Maybe it was caused by me, only wrote this before.
```
    if (sensorsFetch.pending) {
      console.info('pending', sensorsFetch);
      return <Component sensors={defaultSensors} />;
    } else if (sensorsFetch.fulfilled) {
      console.info('fulfilled', sensorsFetch);
      return <Component {...rest} sensors={sensorsFetch.value || defaultSensors} />;
    }
```
