### ISSUE TITLE
Auto parse html in response caused react-router not working.

### ISSUE THREAD

**Issue by stupidisum** [heroku/react-refetch#138]
As I said in #137 `http-server` will return blank 404 for unimplemented api. react-router works fine.
But in my production env, nginx will return a `404.html` or a response with this contenxt, and react-router is not working.
After comparision, we let nginx return blank 404, too. And react-router works again.

So, I think it's re-fetch tried to parse a `404 response` and somehow corrupted react-router.

Here is the response header:
```
Connection:keep-alive
Content-Type:application/xml
Date:Mon, 18 Jul 2016 06:15:11 GMT
Server:AmazonS3
Transfer-Encoding:chunked
Via:1.1 a6b36ab8d09eaf482b5f76d2c61332af.cloudfront.net (CloudFront)
X-Amz-Cf-Id:y2o_whLU9yRF_ALHljMk9MvSceZMWQDvbKsMY-20JKlNX8jYtZSQ9g==
X-Cache:Error from cloudfront
```

**Comment by stupidisum** [comment]
Here is the 404 content. Also, when response content is a 200.html, it will cause react-router not working
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>api/sensors</Key>
<RequestId>0FD0FFD66C031E13</RequestId>
<HostId>+DErSsifskDUSdFVTj2ywdImM3VPX7eUQ9I+L85TYJ3TG3OJDdsXknPL1EyzkZmf1KmrLGbkA7o=</HostId>
</Error>
```

**Comment by ryanbrainard** [comment]
Sorry for the delay. I'm pretty sure this has to do with both of these responses being non-JSON. See https://github.com/heroku/react-refetch/blob/master/src/utils/handleResponse.js#L8 where the pasrsing happens and the associated `TODO`. Can you have your server always return a well-formed JSON response, even for a 404? I really don't want to special case 404 in RR, but if you want to tackle supporting other content types, I'd welcome PRs.

**Comment by stupidisum** [comment]
Yes, I figured it out. I solved this by adding my own handleReponse.

**Comment by ryanbrainard** [comment]
Cool, that works too! :)
