### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by ryanbrainard** [heroku/react-refetch#148]
The 1.0.0-beta is getting long in the tooth. We should draw a line in the sand and cut a 1.0.0 release. We can always add more things in future releases, but just wanted to open this issue in case anyone who has been using the beta has been experiencing any instability that would not be ready to call it GA. If so, please comment here and open an issue for whatever it is.

cc: @jsullivan, @nfcampos, @eyalw, @passcod

**Comment by nfcampos** [comment]
It's been working great for me, haven't found any issues with it

**Comment by jsullivan** [comment]
+1 for promoting beta to 1.0.0 proper. Maybe give it another few days for folks to chime in, though?

**Comment by loris** [comment]
+1

**Comment by ryanbrainard** [comment]
Just bumped the version to 1.0.0 and slapped on the fancy new logo.
