### ISSUE TITLE
PromiseState.refresh should return a new PromiseState

### ISSUE THREAD

**Issue by nfcampos** [heroku/react-refetch#149]
PromiseState.refresh should return a new PromiseState because this way a `shallowEqual` comparison of the props in the wrapped component erroneously returns `true` even though the PromiseState changed

**Comment by nfcampos** [comment]
(and the current behaviour goes against the docs ;) https://github.com/heroku/react-refetch/blob/master/docs/api.md#promisestate)
> Properties should be treated as read-only and immutable. If the Promise enters a new state, a new PromiseState object is created.

**Comment by ryanbrainard** [comment]
Good catch! I can put together a quick fix
