### ISSUE TITLE
Request.mode support

### ISSUE THREAD

**Issue by ryanbrainard** [heroku/react-refetch#154]
Allow `Request.mode` to be set for no-cors (and other modes) support.

See https://github.com/heroku/react-refetch/pull/45

cc: @Adam-Burke

**Comment by yhjor1212** [comment]
+1

**Comment by alexcanessa** [comment]
+1

Any updates on this?

**Comment by ryanbrainard** [comment]
Released in 1.0.4: https://github.com/heroku/react-refetch/releases/tag/v1.0.4
