### ISSUE TITLE
Accessing context in buildRequest

### ISSUE THREAD

**Issue by loris** [heroku/react-refetch#159]
What I'm looking to do is quite simple and seems pretty common when using `react-refetch` in a real-world application, however I couldn't find a way to do it in a DRY/non-bloated way:
All my `react-refetch` requests are authenticated using some data (jwt tokens) stored in the react context. I'm aware I can access context when defining requests by using `contextTypes` on the wrapped component as described in the documentation, but it would require me to do this for every components using `react-refetch` in my app (I have hundreds). It would be better to have this done once in the `buildRequest` method. Right now, my work around is to store authentication data in the `window` object instead of context, but it looks pretty un-react.
How would you guys do it?

**Comment by kieranja** [comment]
So you can implement some conditional checking into handleResponse which will check to see if the page is currently /login and if it is you can access the body and use sessionStorage to store the JWT.


handleResponse(response) {
    if (response.url == '/api/auth') {
       sessionStorage.setItem('token', response.data);
    }
}
`

**Comment by loris** [comment]
Hi @kieranja thanks for the heads up. This is already what I'm doing (using `localStorage` actually), and I will keep on doing this if this looks like a proper way to do this. It just doesn't feel very `react` to store data in globals, outside of state, props and context.

**Comment by kieranja** [comment]
@loris No problem! Absolutely - ultimately there is going to be some global state. This library itself actually uses functions such as fetch which are on the global scope (can see it's binding to window.)

The demo also mentions using a global function (getToken) or something along those lines. My login page is non-react (external site) which has to set a cookie with the access token. Eventually we'll move it over to react. However, I simply read the cookie using cookie.get('...')

**Comment by ghempton** [comment]
This seems sub-optimal to require a global here. Seems like it would be good to have a hook to apply defaults to mappings that has access to the context.

**Comment by ryanbrainard** [comment]
I agree it would be nice, but wondering if it would be better done in userspace with a function that wraps your mappings instead:

```js
static transform(mapPropsToRequestsToProps) {
  return (props, context) => {
    const mappings = mapPropsToRequestsToProps(props, context)
    // manipulate mappings with context here
    mappings['totalStatsFetch'] += context['test']
    return mappings
  }
}
```

Yes, you'd have to repeat this in each `connect`, but would be explicit and at least would be a workaround until if/when a hook is added. Happy to accept PRs if someone's up for it.

**Comment by ghempton** [comment]
That approach breaks down for mappings to functions.

**Comment by ghempton** [comment]
Is there any reason why we couldn't just continue to propagate the context into `refetchDatum`, further down the chain, and pass it in as an additional argument to `buildRequest`?
