### ISSUE TITLE
Error: Warning: setState(...): Can only update a mounting component.

### ISSUE THREAD

**Issue by mymtwcom** [heroku/react-refetch#168]
I'm rendering components on server and seeing this error:
```
Warning: setState(...): Can only update a mounting component. This usually means you called setState() outside componentWillMount() on the server. This is a no-op. Please check the code for the Refetch.connect(FlowDetailPage) component.
```
I thought that I will can render them first on server, then send requests from client, for getting data if it's needed.  Do I have such ability?
my code too:

```
export default connect(props => ({
  flowDetailFetch: `/api/v1/${props.route.slug}`
}))(FlowDetailPage);
```
And I also need in redux in some places:
```
import ReactDOM from 'react-dom';
import configureStore from './redux/configureStore';

const initialState = window.__REDUX_INITIAL_STATE__ || {};
const store = configureStore(initialState);

delete window.__REDUX_INITIAL_STATE__;

const component = (
  <Provider store={store}>
    <Router history={browserHistory} routes={routes} />
  </Provider>
);
ReactDOM.render(
  component,
  document.getElementById('app')
);
```

**Comment by ryanbrainard** [comment]
As mentioned in https://github.com/heroku/react-refetch/issues/57, there is no explicit support for server-side rendering. If you'd like to tackle it and send a PR with any changes or documentation, it would be welcome, but so far we've never needed it, so there is currently no support for it.
