### ISSUE TITLE
Feature request: Query params

### ISSUE THREAD

**Issue by ashtuchkin** [heroku/react-refetch#17]
Nice library, thanks for creating it!

What do you think about adding some convenience features?

### Url query params
```javascript
connect((props) => ({
  data: {
    url: "/api/data",
    query: { from: props.from, limit: props.limit }  // => "/api/data?from=xxx&limit=yyy
  }
}))(Component)
```

**Comment by nurasadim** [comment]
okey

**Comment by hnordt** [comment]
I like both ideas. +1

Just one suggestion, instead `data`:

```js
connect(({ name }) => ({
  barFetch: {
    url: `/foos/${name}`,
    query: { foo: verifyFoo(), bar: verifyBar() }
    transform: ({ foos, page }) => ({ bars: foos, page  }),
    then: (foo) => `/bar-for-foos-by-id/${foo.id}`
  }
}))
```js

**Comment by ashtuchkin** [comment]
That's even better! :)

**Comment by hnordt** [comment]
@ryanbrainard,

If you approve the syntax I'll be happy to create a pull request.

**Comment by ryanbrainard** [comment]
To do the data transform, you should be able to use then() on the PromiseState instead of on the request in connect(). The latter will fire off a new request, which is probably not what you want.

**Comment by ryanbrainard** [comment]
@nhordt do you mean call the 'query' attribute 'data' (and maybe also share it with 'body') like jquery does? I wasn't following your example in relation to the issue.

**Comment by ryanbrainard** [comment]
Also, can we please break this into two separate issues? :)

**Comment by hnordt** [comment]
@ryanbrainard I think transforming data on PromiseState is ok, better than add a new prop.

About `query`. My miss typed the `verify` part. Another example:

```
connect(({ name }) => ({
  barFetch: {
    url: `/foos/${name}`,
    query: { foo: 'bar', bar: 'foo' }
  }
}))

// barFetch should request /foos/${name}?foo=bar&bar=foo
```

**Comment by ashtuchkin** [comment]
Moved discussion of transform functions to #21

**Comment by ryanbrainard** [comment]
I've been thinking about this, I've decided to decline on this feature for the following reasons:
1. The query is part of the URL. Having it be in a separate attribute can lead to confusion.
2. It requires the use of request object syntax. The URL string request syntax should always be preferred for simplicity. 
3. I agree that declaring the query params as an object/hash is good (I do this myself), but I think that converting it to a query string is something that should be done by an explicit function. We could provide something like this in this library, but I'm sure there are several existing libraries that already provide such a facility (e.g. jQuery's `$.param()`), so I don't think there would be much value in implementing another one. ES6 string templates/interpolation make this even nicer to use to include in a string.
