### ISSUE TITLE
Jest testing fails because fetch is type checked even if not used.

### ISSUE THREAD

**Issue by aaronschwartz** [heroku/react-refetch#175]
I'm trying to write a test for my component using Jest/Enzyme.
I'm following the convention that is specified in the README.

The problem I'm having is that the test fails with:
`Invariant Violation: fetch must be a function. Instead received a undefined.`

I'm only importing the unconnected component to be used in the test, but since the whole file is being imported, `connect` is trying to type check the `fetch` function and fails because there is no `window.fetch` (or global, etc) set in the environment.

```
class Profile extends React.Component {
...
}

export { Profile as _Profile }

export default connect(...)(Profile)
```
```
import {_Profile} from './Profile.js'
// ... tests
```

I've tried setting up `global.fetch = ()=>{}` in Jest but it's too late by then since the import has already failed before I can set it.

Any tips on how to deal with this? Thanks.

**Comment by ryanbrainard** [comment]
I think I'm breaking some jsdom best practices here and surely could be improved, but this what I'm doing in setup:

```js
import { jsdom } from 'jsdom'

// maybe not needed, but i had some scripts (removed) in the head tags that needed to be loaded
global.document = jsdom('<!doctype html>' +
  '<html>' +
    '<head>' +
    '</head>' +
    '<body/>' +
  '</html>'
)
global.window = document.defaultView
global.navigator = window.navigator
global.self = window

window.fetch = function () {
  throw 'DO NOT CALL fetch() FROM TESTS'
}

window.Request = function () {
  throw 'DO NOT CALL Request FROM TESTS'
}
```

**Comment by ryanbrainard** [comment]
Closing this, but re-open if needed.

**Comment by aaronschwartz** [comment]
I finally found the equivalent setup in jest. Posting for future onlookers.

Create a `setupJest.js` file:
```
// setupJest.js
global.fetch = () => {
    throw 'DO NOT CALL fetch() FROM TESTS';
};
global.Request = () => {
    throw 'DO NOT CALL Request FROM TESTS';
};
```
Add to your `package.json` file:
```
// package.json
"jest": {
  "setupFiles": [ "./setupJest.js"]
}
```

**Comment by ryanbrainard** [comment]
@aaronschwartz thanks for adding that!

@nfcampos I'm thinking we might want to move these type checks to happen at fetch time rather than connect time to avoid this kind of issue and workaround in tests. Perhaps there could be a test mode or something too, but I'd rather avoid that. Just thinking out loud, but would be interested to hear your thoughts.

**Comment by nfcampos** [comment]
@ryanbrainard sorry for the late reply, yes I do agree, we should be checking only at fetch time, should make testing less fiddly.
