### ISSUE TITLE
Allow value in identity requests to be a function

### ISSUE THREAD

**Issue by ipanasenko** [heroku/react-refetch#177]
Currently in identity requests it's possible to pass a `Promise` into `value`, which is awesome, but if promise is returned from function, this function is called every time route changes, which leads to extra requests, even if user id didn't change, e.g. when navigating from `/user/:id/pulls` to `/user/:id/commits`

```js
const fetchUser = id => fetch(`/users/${id}`);

connect(props => ({
  user: {
    value: fetchUser(props.match.params.id),
    comparison: props.match.params.id
  }
}))(Profile);
```

This can be solved if `value` can be function:

```js
const fetchUser = id => fetch(`/users/${id}`);

connect(props => ({
  user: {
    value: () => fetchUser(props.match.params.id),
    comparison: props.match.params.id
  }
}))(Profile);
```

Function passed into `value` should only be invoked if comparison changed.
What do you think?

**Comment by nihakue** [comment]
What about this?

```js
function mapPropsToRequestsToProps(props) {
  return {
    fooFetch: {
      get value() {
        return api.foo(props.id);
       }
     }
   }
}
```
 
I'm not sure this will actually reduce the number of requests, but it will cause value to be lazily evaluated.

**Comment by ipanasenko** [comment]
Nice idea, but I think it will not work, as there will be at least three requests performed. In current code, `mapping.value` is accessed three times in one function, each time making a request

**Comment by nihakue** [comment]
Could always memoize the promise! :p
```js
function mapPropsToRequestsToProps(props) {
  let foo;
  return {
    fooFetch: {
      get value() {
        return foo || (foo = api.foo(props.id))
       }
     }
   }
}
```

**Comment by slorber** [comment]
is someone working on supporting this feature? @ipanasenko ?

**Comment by ipanasenko** [comment]
@slorber I've started, but abandoned it for now. I really hope @ryanbrainard will find time to implement this himself :)

In case someone wants to have a look at my progress, here it is: https://github.com/heroku/react-refetch/compare/master...ipanasenko:feat/identity-function

**Comment by ipanasenko** [comment]
Okay, I think I've made it. Everyone, you are welcome to review and comment: https://github.com/heroku/react-refetch/pull/192
