### ISSUE TITLE
Changing props does not cancel previously refreshing configuration

### ISSUE THREAD

**Issue by aaronschwartz** [heroku/react-refetch#180]
Setup:
```
connect(props => ({
  dataFetch: {
    url: `api/${props.id}`
    refreshInterval: 5000
  }
}))(...)
```

Steps:
1. Load the component.
2. Wait for a refresh and before the refresh finishes resolving:
2. Update the props to the component to change `id`. (don't unmount/remount, just update the props).

Result:
It calls `/api/new-id` once but then the refresh finishes and all subsequent refreshes are called with `api/old-id`.

It appears the refresh completing is overwriting the internal `dataFetch` that contains the new props.

I think in this case, the old refresh should be cancelled or ignored and re-setup with the new props.

**Comment by ryanbrainard** [comment]
Fixed by #181
