### ISSUE TITLE
ios safari and chrome formdata requests not working

### ISSUE THREAD

**Issue by rohit-ravikoti** [heroku/react-refetch#187]
Hi,
We are facing a major issue in ios (safari and chrome), and desktop safari where FormData being used for the body is not sending any api requests. Here is an example:
```
{
    url: `/register`,
    method: "POST",
    headers: { "Content-Type": undefined },
    body: formData
  };
```

Has anyone encountered this issue before? Thanks!

**Comment by ryanbrainard** [comment]
This library only supports JSON data. It's something we'd like to expand to other data type, but only JSON for now.

**Comment by rohit-ravikoti** [comment]
I figured out how to work around this for anyone who might be having similar issues:

I was using the `buildRequest` default which was returning a new `Request` object-- safari and ios do not support this. So, I implemented a custom fetch that took an object with `url` and `options` and passed it in to fetch. From `buildRequest`, I return the object in the specified format.

Hope it helps!

**Comment by ryanbrainard** [comment]
Ah, you were using `buildRequest`. Your original issue did not say that. Glad to resolved the issue.
