### ISSUE TITLE
How to fetch data manually in TypeScript?

### ISSUE THREAD

**Issue by makamekm** [heroku/react-refetch#189]
I expect it to be working like this:
```
const rightData = await this.props.refetchNewData();
```

But I've got `undefined`. 

I tried to use the following method:
```
await this.props.refetchNewData();
let data = await new Promise((r, e) => {
  this.props.newData.then(v => r(v)).catch(v => e(v))
});
```
But Promise don't resolve anything. Please, help!

**Comment by ryanbrainard** [comment]
This library does not return `Promise`s, but rather `PromiseState`s, so things like `await` are not going to work`. Please see the readme for examples.
