### ISSUE TITLE
Support imperative promise-based API

### ISSUE THREAD

**Issue by slorber** [heroku/react-refetch#191]
Hi,

I'd like to avoid passing directly urls and fetch props directly to react-refetch, but instead feed it with a promise that I build myself.

I think the lib would be more flexible in general, and also easier to adopt for existing projects which already expose an imperative API returning promises. Also I don't really like to pass urls in HOC as this may make API refactorings harder and lead to some code duplication (or a weird "fetchArgsFactory" abstraction)

I imagine an API like that:

```javascript
export default connect(props => ({
  userFetch: {
    fetch: MyImperativeApi.fetchUser,
    fetchArgs: props.userId, // or array if multiple arguments needed
  },
}))(Profile)
```

The parameters in `fetchArgs` will be injected into `MyImperativeApi.fetchUser(userId)`. 
The fetch function would be called again only when the fetchArgs / userId changes (compared with deep comparison, this is what other libs like Apollo do to trigger refetch).

I'm ok to make a PR for such an API if validated

**Comment by ryanbrainard** [comment]
I'd rather go a route more like https://github.com/heroku/react-refetch/issues/177 so that you could achieve this just by using `value` and `comparison`:

```javascript
export default connect(props => ({
  userFetch: {
    value: MyImperativeApi.fetchUserPromise,
    comparison: props.userId, // or array if multiple arguments needed
  },
}))(Profile)
```

This would work now, except that `value` will eval every time and not respect `comparison`. The idea in https://github.com/heroku/react-refetch/issues/177 is to only eval `value` if the `comparison` changes.

**Comment by slorber** [comment]
thanks @ryanbrainard i'm fine with such an API even if it's not as clear it's flexible enough so that I can provide my own abstraction

**Comment by ryanbrainard** [comment]
Just updated the example above to actually pass the prop to `fetchUserPromise` and make it a function. Sorry, I wasn't thinking through it before -- this should make things clearer. I think this will actually be a more flexible and powerful API (and more consistent with what actually exists now).

**Comment by slorber** [comment]
that that API is fine for me
