### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by davydof** [heroku/react-refetch#200]
2️⃣ 0️⃣ 0️⃣  issue 😋 

Hello!

It will be awesome if someone add the definitions for TypeScript 👍 

Thanks :-)

**Comment by rjhilgefort** [comment]
Bump! (Sorry to be a bother).

Thanks for the awesome library!

**Comment by lmontoute** [comment]
We wrote some types for this library actually, I can look into cleaning it up when I get some spare time to do so. `PromiseState` was straightforward enough, but `mapPropsToRequestsToProps` is a little trickier.

**Comment by hburrows** [comment]
@lmontoute Thanks for sharing.  I used `dts-gen` to bootstrap an initial declaration file and this is much better; I immediately knew I needed a parameterized PromiseState which you already have.  I'll definitely try to add more support and contribute back.  This package could really benefit from typescript (and flow) declarations.  I'm surprised nothing yet exists in DefinitelyTyped.  Let's change that!

**Comment by rjhilgefort** [comment]
Just want to chime in and say that I appreciate you guys working towards this! I'm not currently working on the project I was that needs this, but I love this library and look forward to having typing when I jump back. If there's still something to do when I get back to it, I'd be happy to help!

**Comment by lmontoute** [comment]
Got around to this today :)

Updated the above with a full declaration file. Will look at submitting a PR
