### ISSUE TITLE
Pass props to default handlers

### ISSUE THREAD

**Issue by dprentis** [heroku/react-refetch#202]
Would be useful to pass the component props to default handler methods such as `buildRequest` and `handleResponse`.

AFAIK currently the only way to do this, is to hold props in a closure, but that makes the code pretty convoluted:
```
import { connect } from 'react-refetch';

export const myConnect = fn => {
	let props = null;
	const defaults = {
		buildRequest: mapping => {
			// use props here
		},
		handleResponse: response => {
			// use props here
		},
	};
	return Component => connect.defaults(defaults)(_props => fn((props = _props)))(Component);
};
```
Maybe I'm just missing something obvious - any feedback appreciated. Otherwise great library!

**Comment by dprentis** [comment]
Any thoughts?

**Comment by ryanbrainard** [comment]
All the props handling should be done in `mapPropsToRequestsToProps`, which creates the `mapping` to be passed to `buildRequest`. Ideally, `buildRequest` should be generic enough to deal with any mapping and no longer need the props. If you do want to pass them along for some reason, I'd probably recommend stuffing them in `meta`, which could then be accessed inside of `buildRequest`. Would this work? I'm going to close this, as I don't think there's a use case for this, but if there is, please let me know and we can re-open and discuss it.

**Comment by dprentis** [comment]
Ok, thanks for the reply. My use case is, I need to pass an authentication header with all my requests to the api. This token is stored in a mobx store. I'm using the `buildRequest` handler to do this, so I need to access the store inside the handler.

The store is being injected into the component using a mobx-react Provider, so is available in props. The logical solution is to make props accessible to the `buildRequest` handler, because otherwise I would have to either:
a) make the store globally accessible and import it directly to use in the handler (not so nice IMHO)
b) pass the store prop to the handler explicitly for each and every request, through meta. Also not nice IMHO.

Similarly, I have a `handleResponse` handler, which also accesses the store.

Anyway, never mind - I will stick with my current solution for now and consider the other two options.

**Comment by ryanbrainard** [comment]
@dprentis Ah, ok. Yeah, I think how you are going it now makes the most sense. If this is a common need, I could see doing something like configurable pre/post hooks for doing common things like this, but that is essentially what `buildRequest`/`handleResponse` is now, so probably fine to keep doing it there. Perhaps exposing the default implementations of [`buildRequest`](https://github.com/heroku/react-refetch/blob/master/src/utils/buildRequest.js)/[`handleResponse`](https://github.com/heroku/react-refetch/blob/master/src/utils/handleResponse.js) would help so you could use that instead of re-inventing (or copy/pasing) the wheel in your implementation?

**Comment by dprentis** [comment]
Would it be difficult to let `connect.default` optionally accept a function of props, that would return the configuration object? eg.
```
const refetch = connect.defaults(props => {
  buildRequest: function (mapping) {
    // make request based on mapping and props ...
  },
  handleResponse: function (response) {
    // return value based on response and props ...
  },
});
```
