### ISSUE TITLE
Update PromiseState manually to avoid refresh?

### ISSUE THREAD

**Issue by slorber** [heroku/react-refetch#205]
Hi,

Suppose I have a list of items fetched with react-refetch, if the user deletes an item, I could refresh the whole list, which would be overkill.

Is there an API which permits me to update the PromiseState stored inside react-refetch, so that I can remove my item from the list manually?

Current workaround is to store in my component a "deletedItems" array, so that when iterating on the PromiseState items, I could simply filter the item that just got deleted. This works nice but would be better if this kind of thing was supported in this lib.

Also note this applies to item updates (I would have to store a local "itemsUpdated" array)

**Comment by ryanbrainard** [comment]
No, sorry, there is not an API for this as this would break the one-way data flow model. I can see how it would be helpful, but for keeping the lib simple, I think it’s best to manage this in the app.
