### ISSUE TITLE
POST onClick only sent once

### ISSUE THREAD

**Issue by gioiafueter** [heroku/react-refetch#208]
Hi, I am trying to send a POST request when the user clicks a Button, the on click event gets triggered every time the button is clicked, but the post request is sent only once...

export default RefetchDefault(() => ({
  hostsFetch: {
    url: adex.url(`collect/rtapi/token/${/[^/]*$/.exec(window.location.href)[0]}`),
  },
  deleteHosts: hostnames => ({
    deleteHostsResponse: {
      url: adex.url('collect/rtapi/delete-hosts'),
      method: 'POST',
      body: JSON.stringify({ hostnames }),
    },
  }),
}))(RTApiCreateHosts)

**And the Refetch default:**

import { connect } from 'react-refetch'

const RefetchDefault = connect.defaults({
  cache: 'no-cache',
  credentials: 'same-origin',
  headers: {
    'content-type': 'application/json',
  },
  method: 'GET',
  mode: 'cors',
})

export default RefetchDefault

What am I doing wrong?
Thanks a lot in advance,
Gioia

**Comment by ryanbrainard** [comment]
Try setting `force: true` in the post request. This is happening because your props aren't changing, so the request isn't being made. `force: true` overrides this behavior.
