### ISSUE TITLE
Posting data and having it return as a promise

### ISSUE THREAD

**Issue by fc** [heroku/react-refetch#212]
In the documentation, there is this example:

```
<button onClick={() => this.props.postLike(someSubject)}>Like!</button>
```

Calling `postLike` does not return a promise, it is undefined.

I want to be able to display a toast in some cases after a user submits a form, and in another case, I want to be able to dispatch a redux action once it is completed.

I have found a workaround but it is not really desired, e.g.,
```
  exampleUpdate: body => ({
    exampleUpdateResponse: {
      url: `/example/${body.id}/`,
      method: 'PATCH',
      body,
      andThen: () => {
        message.success('Successfully updated');
        return {};
      },
    },
  }),
```

Is there something I'm missing?  
I get the idea that the library is intended to be as composable as possible but, to me, seems like this should be allowed.

Edit:
Also, I now see the `PromiseStateContainer.jsx` example which appears like it could be adapted to fit my needs.  Closing for now since I believe I can make this work.

**Comment by fc** [comment]
I'm stilling running into problems.  It will create an infinite loop because it triggers a re-render.  To me seems like a bug.  If the `this.props.postLike(someSubject)` callback could return a promise, I think that could make this work.

It looks like it calls `refetchDataFromMappings` here:
https://github.com/heroku/react-refetch/blob/5519f201aa17f590b0e99baf233b88d80e9ef28a/src/components/connect.js#L242

But... it does not look like there would be an easy for it to return a promise.

Thoughts? or, suggestions on what to do? @ryanbrainard

**Comment by fc** [comment]
Aha... using the PromiseStateContainer, I can use shouldComponentUpdate.
```
  shouldComponentUpdate(nextProps) {
    const { ps } = this.props;
    // ps changed, update
    if (ps !== nextProps.ps) return true;
    if (ps) {
      if (
        ps.fulfilled !== nextProps.ps.fulfilled ||
        ps.pending !== nextProps.ps.pending ||
        ps.rejected !== nextProps.ps.rejected
      ) {
        // Status changed, update
        return true;
      }
      // Status did not change, don't update
      return false;
    }

    return true;
  }
```

**Comment by fc** [comment]
ok..clearly I was making this all too complicated.

The simple way to achieve it is:
```
const ConnectedForm = apiConnector({
  updateThing: (body, then) => ({
    updateThingResponse: {
      method: 'patch',
      url: `/thing/${body.id}/`,
      body,
      then,
    },
  }),
})(Form);
```

Then in, for example, your onSubmit handler:
```
          onSubmit={values =>
            updateThing(values, () => {
                // stuff here
            })
          }
```

I still like the idea of it returning a promise from `refetchDataFromMappings` which might be achieved by returning `mappings` from that, then access it as `updateThing(values).then({updateThingResponse})`... but this is not tested.

**Comment by StudioSpindle** [comment]
@fc nice! And how can you access the response header in the callback?

**Comment by StudioSpindle** [comment]
Ah, found it. As per [API documentation](https://github.com/heroku/react-refetch/blob/master/docs/api.md) there is a meta object that can be used:

```
          onSubmit={values =>
            updateThing(values, (values, meta) => {
                const { response: { status } = meta;
                if (status === 500) {
                 // do something to the 'thing'
                 // perhaps also try again...
                }
            })
```

**Comment by StudioSpindle** [comment]
```
({
  myPut: (data, thenCallback, catchCallback) => ({
    myPutResponse: {
      url: 'some-url',
      method: 'PUT',
      body: JSON.stringify(data),
      andThen: (value, meta) => {
       thenCallback(value, meta);
       return {};
      },
      andCatch: (reason, meta) => {
        catchCallback(reason, meta);
        return {};
      }
    }
  })
}),
```
And then in the component:

```
const onSubmitPutSuccess = (value, meta) => {
    const { response: { status } } = meta;
    if ( status === 200) {
       // all good, do something
     }
}

const onSubmitPutError = (reason, meta) => {
    const { response: { status } } = meta;
    if ( status === 500) {
       // do something with the error
     }
}

myPut(
  payload,
  (value, meta) => onSubmitPutSuccess(value, meta), // thenCallback
  (reason, meta) => onSubmitPutError(reason, meta), // catchCallback
);
```
