### ISSUE TITLE
Can you retry a failed request from within render?

### ISSUE THREAD

**Issue by popey456963** [heroku/react-refetch#224]
For example, sometimes our endpoints return errors asking the client to back off for an amount of time.  Is there a way to restart the fetching updates from within a component, even if a past request has failed?

**Comment by ryanbrainard** [comment]
There is nothing to this out of the box, but you could override the `fetch` implementation to do this. See https://github.com/heroku/react-refetch#on-changing-the-fetch-and-request-implementations. This wouldn't be a bad idea as a default option, but unless there isn't a lot of demand, just overriding like this is probably best.
