### ISSUE TITLE
react 16.9, Warning: componentWillMount has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by StudioSpindle** [heroku/react-refetch#231]
With the latest release 16.9 of React deprecated lifecycles are warned by default [source](https://github.com/facebook/react/releases)

This method has also been marked as UNSAFE: https://reactjs.org/docs/react-component.html#unsafe_componentwillmount

Occurences:
[./src/components/connect.js](https://github.com/heroku/react-refetch/blob/884ee2d1cf18179c715b45c47451e577c871d23a/src/components/connect.js#L201)
[./test/components/connect.spec.js](https://github.com/heroku/react-refetch/blob/884ee2d1cf18179c715b45c47451e577c871d23a/test/components/connect.spec.js#L38)

Two options: 
1. There is a codemod script with which you can update the project to use the new methodname `npx react-codemod rename-unsafe-lifecycles` [source](https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles)
2. Or refactor it to `componentDidMount()`

Thoughts?

**Comment by ryanbrainard** [comment]
Merging this into https://github.com/heroku/react-refetch/issues/214.

**Comment by ryanbrainard** [comment]
Released in [3.0.0-1 Beta](https://github.com/heroku/react-refetch/releases/tag/v3.0.0-1)
