### ISSUE TITLE
Fetch rejected but reason empty

### ISSUE THREAD

**Issue by larsgaardsoe** [heroku/react-refetch#232]
I get some weird rejected fetches in my frontend error logs (using Rollbar), and I cant figure out how it happens. For some reason it's rejected without a reason. Is this a bug or what is going on?

````json
{
    "pending": false,
    "refreshing": false,
    "fulfilled": false,
    "rejected": true,
    "settled": true,
    "value": null,
    "reason": {},
    "meta": {
        "request": {},
        "response": {}
    }
} 
````

**Comment by ryanbrainard** [comment]
The problem is likely that the error doesn’t match the expected format of
having either an “error” or “message” field. See code here:

https://github.com/heroku/react-refetch/blob/master/src/utils/errors.js

**Comment by larsgaardsoe** [comment]
Thank you very much for the fast response. I'm sure you're right.

And thanks for the awesome library!
