### ISSUE TITLE
RR with Redux

### ISSUE THREAD

**Issue by hnordt** [heroku/react-refetch#24]
I'm opening this issue to start a discussion on how to use both RR and Redux together.

My first idea is something like:

```js
class Foo extends React.Component {
  componentWillReceiveProps(nextProps) {
    const { dispatch } = this.props; // Injected by Redux
    if (nextProps.fooFetch.fulfilled) { // Injected by RR
      dispatch(updateFoo(nextProps.fooFetch.value)); // updateFoo is an action and we pass PS.value as payload
    }
  }
}

// normal RR/Redux connects...
```

I don't see any problems with this approach. @gaearon thoughts?

Worth noting: if your app don't need to maintain local state, Redux/Flux is optional (https://github.com/heroku/react-refetch#motivation)

**Comment by frontsideair** [comment]
I think it should just work, unless Refetch and Redux `connect` imports clash. I imagine passing your component to one `connect` and pipe it to the next one and you should have all required props available.

I'll keep an eye on this discussion though.

**Comment by ryanbrainard** [comment]
You probably also want to make sure that the props actually changed or at least that the PS changed from pending to fulfilled; otherwise, you'll end up calling the action multiple times. 

Without thinking about it too much, this pattern feels a bit too imperative to me. If this really is a pattern that people would like to use, I'd like to see something more declarative and/or reactive. Furthermore, I'd really like to see use cases/stories so we are designing this to solve real world problems instead of starting with the technology. 

Thanks for kicking off this discussion.

**Comment by hnordt** [comment]
@ryanbrainard connecting both RR and Redux to the same component doesn't worked well on my tests. Handling updates inside `componentWillReceiveProps` was a mess.

I propose a different approach:

```jsx
connect((props, state, dispatch) => ({
  projectsFetch: '/api/projects.json',
  someStateFromRedux: state.someStateFromRedux,
  onSomething: () => dispatch(someReduxAction())
}), store)(Projects)
```
Maybe you can enable mapping state and dispatch as additional properties. As store will be available through `this.context` maybe you can check for it and enable state/dispatch mapping.

**Comment by boyswan** [comment]
+1

**Comment by hnordt** [comment]
As I can't make RR work with Redux for now I've created a side project based on RR ideas for cases you really need Redux.

Here is a sample usage: https://github.com/hnordt/reax/blob/f148edeb1fa870c12f0b7a26c603101fa4990cb2/src/projects/containers/Projects.js

Repo: https://github.com/hnordt/reax-api

While it's already working and I'm using in production, there are many cases to be covered yet.

**Comment by anaibol** [comment]
+1

**Comment by tomasdev** [comment]
@hnordt where did your project go!? I need it :)

**Comment by ryanbrainard** [comment]
Closing this out as it seems like the discussion has died off, but feel free to re-open if needed.

**Comment by tomat** [comment]
Was also looking for a solution to this, and ended up writing my own (of course :-P), might be interesting for others ending up here, at least for inspiration:

https://github.com/tomat/react-reflorp

Basically I really like the way Refetch does things, but I still wanted less boilerplate, and to keep things in the Redux store. Ended up with something of an ORM, where it keeps track of which component needs which entity with which id, and stores them separately in Redux, but still allowing use of regular Redux and Refetch within the same decorators. Not in any way production ready, though :-)

Feel free to open an issue over there if you have a question...
