### ISSUE TITLE
Rejected promises don't get error messages in IE8

### ISSUE THREAD

**Issue by imjoehaines** [heroku/react-refetch#37]
Hi,

I'm not sure if IE8 is supposed to be supported or not, but after polyfilling all of the things this library almost works perfectly.

The only issue I've encountered is that IE8 refuses to accept a message for the [error that is thrown when rejecting promises](https://github.com/heroku/react-refetch/blob/master/src/components/connect.js#L86-L88) because of the second `id` parameter. If you delete the `id` then everything seems to work fine.

As far as I can tell `Error` isn't supposed to have a second argument anyway so I'm not sure what the `id` is for, but it could be handled with a custom error type that does take a second argument - this could also be useful to support passing more than just a message on a server error.

**Comment by ryanbrainard** [comment]
Good catch. I thought for sure I remember seeing `id` in the doc, but you're right that it is not there. I'm thinking I can instead do this:

```
e = new Error(message)
e.id = id
throw e
```

It's a little dirty to set the `id` like that as a field, but just don't want to loose that data in case someone needs it. I just tested this in the console with Chrome and it works. Would you so kind to try it on IE8 (sorry, I don't have easy access to IE8)?

**Comment by imjoehaines** [comment]
Yeah that works fine, IE sets the message and id properly.

Would you be willing to change the name from `id` to something more generic, or add a new field for additional information about an error (maybe `context`)? We're dealing with a legacy application that often passes arbitrary data back from the server on errors and it would be nice to be able to handle the same cases without having to refactor things *too* much to begin with.

We could just attach it to `id` but it'd be nice to have a proper place for that sort of thing to live.

**Comment by ryanbrainard** [comment]
Thanks for testing that out.

Yes, I'd be happy to make it more generic. `id` is a Heroku API-specific
thing where we put error codes, and probably doesn't belong in here. What
I'm thinking is placing the entire original error in a Java-style `cause`
field, so then you can get to anything you want. For example, `id` would be
at `e.cause.id` and your arbitrary fields would also be accessible. Would
that work?

**Comment by imjoehaines** [comment]
No worries.

Yeah, that sounds like it would work perfectly!

**Comment by ryanbrainard** [comment]
Released in [v0.7.0-beta.0](https://github.com/heroku/react-refetch/releases/tag/v0.7.0-beta.0)
