### ISSUE TITLE
Offline Support

### ISSUE THREAD

**Issue by hnordt** [heroku/react-refetch#40]
I'm working on a project that needs offline support and I don't want to use Flux, because all state is saved on server-side and I don't wanna duplicate/manage local state.

Would be awesome if we can provide our own implementation of `handleResponse`, so we can implement something like this:

```js
// myOwnHandleResponse.js

import localforage from 'localforage';

const getRequestId = request => {
  // TODO: md5 or something like that :P
  return `${request.url}.${request.method}.${JSON.stringify(request.headers)}`;
};

// On response success update offline cache and return json
// On response failure warn and return the cached json
const handleResponse = (request, response) => {
  const requestId = getRequestId(request);
  if (response.status >= 200 && response.status < 300) { // Or response.ok
    const json = response.json();
    // localforage.setItem() resolves the value that was set :)
    return localforage.setItem(requestId, json).catch(error => {
      console.warn('Failed to update offline cache', { requestId, request, error });
      return json;
    });
  } else {
    return localforage.getItem(requestId);
  }
};

export default handleResponse;
```

We'll need to implement a timeout in React Refetch and implement a way to handle POST/PUT/DELETE requests.
It's just the initial idea. Toughts?

**Comment by ryanbrainard** [comment]
> a way to handle POST/PUT/DELETE requests.

Set the `method` in the request.

**Comment by ryanbrainard** [comment]
I'm still idly noodling on how to handle custom request and response handling. There's several way to do it, but so far not totally satisfied with something that both retains reasonable defaults and gives users enough power. Good to see more use cases like this though.

**Comment by hnordt** [comment]
@ryanbrainard it's not so simple, offline POST/PUT/DELETE requests need to be queued, so we can dispatch them when we back online. We'll need to do something like:

```js
const handleRequest = request => {
  if (request.method === 'POST' && isOffline) {
    return localforage.setItem('queue', [...queue, request]);
  }
  // ...
};
```

**Comment by hnordt** [comment]
@ryanbrainard,

Something that is simple and very flexible:

Change:

```js
return fetched.then(handleResponse).then(onFulfillment(meta), onRejection(meta))
```

```js
function buildRequest(mapping) {
  return new window.Request(mapping.url, {
    method: mapping.method,
    headers: mapping.headers,
    credentials: mapping.credentials,
    redirect: mapping.redirect,
    body: mapping.body
  })
}
```

```js
function handleResponse(response) {
  const json = response.json() // TODO: support other response types
  if (response.status >= 200 && response.status < 300) { // TODO: support custom acceptable statuses
    return json
  } else {
    return json.then(cause => Promise.reject(newError(cause)))
  }
}
```

To:

```js
return fetched.then(handleResponse.bind(null, request).then(onFulfillment(meta), onRejection(meta))
```

```js
function buildRequest(mapping) {
  if (options.buildRequest) {
    return options.buildRequest(mapping)
  }
  return new window.Request(mapping.url, {
    method: mapping.method,
    headers: mapping.headers,
    credentials: mapping.credentials,
    redirect: mapping.redirect,
    body: mapping.body
  })
}
```

```js
function handleResponse(request, response) {
  if (options.handleResponse) {
    return options.handleResponse(request, response)
  }
  const json = response.json()
  if (response.ok) {
    return json
  } else {
    return json.then(cause => Promise.reject(newError(cause)))
  }
}
```

**Comment by ryanbrainard** [comment]
@hnordt The reason I don't want to do it that way is that then it applies to everything in `connect` and not granular to one request/mapping. Of course we could put `buildRequest` and `handleResponse` on the request/mapping, but there is usually a strong correlation between the two (e.g. `text/csv` headers and CSV handers) and it would be nice to have them be applied together. Perhaps this is simple as doing something like `{ handlers: { request: ..., response: ... } }`, but then I'd still want the ability to be able to provide defaults like you did at the `connect` level. I know that sounds a bit contradictory, but the point is that the handlers should be primitives on the mappings and then what goes at the connect level (or maybe one level within) should be selecting the defaults of those mappings. If you want to take a stab at this, I would recommend opening a pull request.

**Comment by hnordt** [comment]
@ryanbrainard I like the idea of having defaults. The problem is that way we'll need to implement every possible type of response (CSV, PDF, offline caches, etc.).

I think React Refetch should do the basic, i.e. handle common JSON, if you need something specific, you are free to enhance the connect.

Thats exact same idea from Redux's store enhancer:

> A store enhancer is a higher-order function that composes a store creator to return a new, enhanced store creator. This is similar to middleware in that it allows you to alter the store interface in a composable way.

> Store enhancers are much the same concept as higher-order components in React, which are also occasionally called “component enhancers”.

**Comment by hnordt** [comment]
@ryanbrainard updated my previous comments, please read again :P

**Comment by ryanbrainard** [comment]
@hnordt I think we're talking about two different kinds of "defaults." I'm not talking about different default handlers (e.g. json. csv, etc), but rather `connect`-level, user-provided default for the requests within. 

For example, it can see it being helpful do something like this to apply a default `refreshInterval` to all request mappings:

```jsx
connect(({ userId }) => ({
   userFetch: `/users/${userId}`,
   likesFetch: `/users/${userId}`/likes,
}), { refreshInterval: 1000 })
```

similarly, you could do something like this for a default `handler`:

```jsx
connect(({ userId }) => ({
   userFetch: `/users/${userId}`,
   likesFetch: `/users/${userId}`/likes,
}), { handler: (response) => {...} })
```

which is kind of like what you are suggesting, but what I'm saying is that that is really just a convenience for the true expanded form of

```jsx
connect(({ userId }) => ({
   userFetch: {
     url: `/users/${userId}`,
     handler: (response) => {...}
   },
   likesFetch: {
     url: `/users/${userId}`/likes,
     handler: (response) => {...}
   }
}))
```

My point is just that the handler primitive should be at the request mapping level, not the `connect` level. We could also support `connect`-level defaults, but those would not be handler-specific.

Make sense or more confusing now? :)

**Comment by ryanbrainard** [comment]
[v1.0.0-beta.0](https://github.com/heroku/react-refetch/releases/tag/v1.0.0-beta.0) has the ability to change the `buildRequest`, `fetch`, and `handle Response` implementations, which should make this possible now. Feel free to open another issue if there's something that that does not provide, but I'll like to have the conversation in that context.
