### ISSUE TITLE
Passthrough meta on all requests

### ISSUE THREAD

**Issue by ryanbrainard** [heroku/react-refetch#42]
[Currently](https://github.com/heroku/react-refetch/pull/41), `meta` only works if `value` is also set (i.e. only for identity requests). I'm thinking that a better way would be for `meta` to work for URL-based requests too and for `request` and `response` to be merged into `meta`. This would allow applications to add arbitrary metadata to any request and make it accessible to the component. I don't have a great use case of that off hand, but I like that it makes identity requests more "normal." The downside I see that `meta` currently allows any data type, but if we go this route, it would have to be an object. Thoughts?

**Comment by jsullivan** [comment]
LGTM.
