### ISSUE TITLE
No way to access json value of an rejected request

### ISSUE THREAD

**Issue by eyalw** [heroku/react-refetch#51]
My server returns status 400 (bad request) intentionally for bad data in a form, and I wish to read the json body that comes along with the response, explaining where that error is and what is it.
It seems the promise API does not allow me to read the error? Please help.. 
(I also tried messing around with Response object, and reading the json() stream, but no success)

![screen shot 2016-02-02 at 11 23 06 am](https://cloud.githubusercontent.com/assets/608669/12744911/83f7e9d6-c99f-11e5-8df9-0dae466233e9.png)

![image](https://cloud.githubusercontent.com/assets/608669/12745030/0a34afde-c9a0-11e5-9671-143c555c870c.png)

**Comment by eyalw** [comment]
**[update]**: see the code below from inside the library, it seems like the lib is expecting a certain format of an error object with id/message/error fields. otherwise, it tried to throw new Error(json) - but the Error api expects a human readable message string, so instead of recieving my json at the other end, i get "[object]"... 

![image](https://cloud.githubusercontent.com/assets/608669/12750365/67c2fc72-c9bf-11e5-9468-87e21fdafb0c.png)

**Comment by ryanbrainard** [comment]
@eyalw If you use the beta version (v0.7.0-beta.0 or higher; v0.7.0-beta.4 is the latest), you can get to the underlying error with the new `cause` attribute on the error. See https://github.com/heroku/react-refetch/pull/38 for details. Closing this now, but re-open if you're still having issues.

**Comment by eyalw** [comment]
thanks!
