### ISSUE TITLE
'comparison' doesn't work when used along with then()

### ISSUE THREAD

**Issue by eyalw** [heroku/react-refetch#53]
The comparison feature does not work if 'then' is also provided.

**Comment by ryanbrainard** [comment]
@eyalw Can you give an example and version number please?

**Comment by eyalw** [comment]
Yes, I will on Sunday when I get back to my work computer,
but for now it was something like 
{
  comparison: ...
  then: (res) => {
     value: res.data,
  }
}

and fetches kept being sent even though comparison value didn't change.
then I removed then() and they stopped.

**Comment by eyalw** [comment]
This is the exact code, i commented the lines that caused the bad behavior (refetching without change to url)

(the then() is the issue, the comparison was an attempt to solve the issue, which didnt work eiher)

![f6098f9c-d3d7-11e5-930b-ee3492ef3b69](https://cloud.githubusercontent.com/assets/608669/13045147/78545eb2-d3da-11e5-9173-0a71b6f2b2c4.png)

**Comment by ryanbrainard** [comment]
Thanks @eyalw, I'll try to look into this week.

**Comment by ryanbrainard** [comment]
@eyalw Happen to have anything to do with the missing commas between your key-values?

**Comment by eyalw** [comment]
no.. the code compiled, not a noob :)
I must have removed them after i commented or something...

**Comment by ryanbrainard** [comment]
Haven't nailed down exactly what is happening, but I was able to reproduce and there's definitely something weird going on here. Hope to dig in more soon.

**Comment by ryanbrainard** [comment]
Oh, I see what it is. The identity request in the then is overwriting the original equality check where the comparison happens. Need to test, but pretty sure that's what's happening.

**Comment by ryanbrainard** [comment]
See #64 for a fix

**Comment by ryanbrainard** [comment]
Workaround in the meantime: set `comparison` again inside the object returned by `then`

**Comment by eyalw** [comment]
Thanks :)

**Comment by ryanbrainard** [comment]
Released in https://github.com/heroku/react-refetch/releases/tag/v0.7.0-beta.3
