### ISSUE TITLE
Add setVariables-like functionality to refetch, as in Relay

### ISSUE THREAD

**Issue by eyalw** [heroku/react-refetch#55]
At the moment the connect() is a function of props alone, so there is no way for an object to change what it currently displays (think about a timeline graph component with a timerange selection - when range changes, different data should be loaded).

If we add somehting something like "setVariables()" which is a little similar to doing setState() on the HOC connect, we can achieve this.
see Relay specs:
https://facebook.github.io/relay/docs/api-reference-relay-container.html

what do you think?

**Comment by ryanbrainard** [comment]
When the user changes the time range selection, can you just update the URL (perhaps a query parameter), which would update the props? This allows all the state to be in the URL, so you can bookmark it, share it, etc, and see the exact same thing. Another (lesser) alternative is to set it in the history state of the URL, which would also be available via props if using React Router. I'm opposed to adding any mutable state in Refetch itself.
