### ISSUE TITLE
Side-effects with the Refetch equivalent of Redux's "action creators"?

### ISSUE THREAD

**Issue by neezer** [heroku/react-refetch#66]
Related to the [section on Posting + Refreshing Data](https://github.com/heroku/react-refetch#posting--refreshing-data), I'd like to push a new browser state after an update action. In my app, there is no separate view for an "edit" action: users can click an edit button, and the row reformats to inputs. My problem lies in redirecting back to the list view after the update action completes.

I have it working with the following:

```es6
import React, { Component } from 'react';
import { connect } from 'react-refetch';
import { authHeader } from 'lib';

class List extends Component {

  // ...

  componentWillReceiveProps(nextProps) {
    const { fetchPref: nextFetchPref } = nextProps;
    const { fetchPref } = this.props;

    if (fetchPref && nextFetchPref && fetchPref.pending && nextFetchPref.fulfilled) {
      this.context.router.push({ pathname: '/admin/prefs' });
    }
  }

  // ...

  render() {
    // omitting the rest of the JSX for the sake of brevity, but this is actually
    // a table where each row has an edit button that invokes `patchPref`
    // with the `id` for the row and the `data` from user input
    return (
      <a onClick={this.props.patchPref.bind(this, id, data)}>edit</a>
    );
  }
}

export default connect((props) => ({
  fetchPrefs: {
    url: '/api/prefs',
    headers: authHeader(),
  },
  patchPref: (id, data) => ({
    fetchPref: {
      url: `/api/prefs/${id}`,
      method: 'PATCH',
      body: JSON.stringify(data),
      headers: authHeader(),
      andThen: () => ({
        fetchPrefs: {
          url: '/api/prefs',
          headers: authHeader(),
          force: true,
          refreshing: true,
        }
      }),
    }
  }),
}))(List);
```

As you can see, I've had to do some `this.props`/`nextProps` checking in `componentWillReceiveProps` to support the behavior I'm after.

What I'd ***like*** to do is define a `then` clause on `patchPref` so that I could invoke it along the lines of:

```es6
this.props.patchPref(id, data).then(() => {
  this.context.router.push({ pathname: '/admin/prefs' });
})
```

The intention being:

> Do all the `react-refetch` stuff defined in `connect` for `patchPref`, then do this other thing.

That would allow me to completely delete `componentWillReceiveProps`.

As the return of `this.props.patchPref()` is `undefined`, and as `then:` and `andThen:` on the `PromiseState` for `fetchPref` only accept objects (for use inside `react-refetch`), it doesn't seem like my desired solution is possible currently.

I don't know if such a thing would be possible, or if there is another/cleaner way of accomplishing the same behavior with the library as it is now.

Was hoping to hear y'alls thoughts on this.

**Comment by eyalw** [comment]
Hey @neezer 
this might be a duplicate of #58  ?

**Comment by neezer** [comment]
Ahh, you're right @eyalw. Missed that. My bad. Will pick up the conversation there.
