### ISSUE TITLE
then/andThen with empty response body

### ISSUE THREAD

**Issue by neezer** [heroku/react-refetch#67]
With the following:

```es6
connect((props) => {
  fetchPrefs: '/api/prefs',
  deletePref: (id) => ({
    doDeletePref: {
      url: `/api/prefs/${id}`,
      method: 'DELETE',
      andThen: () => ({
        url: '/api/prefs',
        force: true,
        refreshing: true,
      })
    })
  }),
})(Component)
```

Invoking `deletePref()` never calls `andThen` on `doDeletePref`.

I've determined this is because my API returns a `204: No Content` with an empty response body. If I change the response to be a `200: OK` and return an empty JSON object, `andThen` fires normally and everything works.

I also tried returning a `200: OK` with an empty body, and the `andThen` did ***not*** fire.

So my guess is that **`andThen` only fires if the response body is not empty**. 

Personally, I think `andThen` should fire if the response was successful, regardless if the response body is present.

NOTE: I encountered the same behavior with `then`.

**Comment by ryanbrainard** [comment]
Definitely sounds like a bug. The presence of a body should not affect the the post-processing. However I tried a quick unit test, but could not reproduce. Perhaps I'm missing something, but in the meantime, could you see if `catch`/`andCatch` work? If they do, is there an error returned?

**Comment by neezer** [comment]
@ryanbrainard `catch`/`andCatch` fails with

> SyntaxError: Unexpected end of input

**Comment by ryanbrainard** [comment]
@neezer Ok, so probably a problem with the JSON parser blowing up and rejecting the promise. What version of whatwg-fetch are you using? Either way, we can handle it in RR, but it wondering why my unit test didn't fail...

**Comment by neezer** [comment]
`"whatwg-fetch": "^0.11.0"`

**Comment by ryanbrainard** [comment]
Hmm, same as me. I can dig in more later. Guessing the problem is in https://github.com/heroku/react-refetch/blob/master/src/components/connect.js#L105-L112 if someone wants to experiment

**Comment by neezer** [comment]
@ryanbrainard That seems like a good guess. Thinking that because `response.body` stream is empty, the line that reads `response.json()` is effectively doing something akin to `JSON.parse("")`, which yields the same error I'm getting.

**Comment by neezer** [comment]
@ryanbrainard Toying around, this fixes the issue for me, though no vote on whether or not this is a good approach:

```es6
function handleResponse(response) {
  if (response.headers.get('content-type') === null)  return;

  var json = response.json(); // TODO: support other response types
  if (response.status >= 200 && response.status < 300) {
    // TODO: support custom acceptable statuses
    return json;
  } else {
    return json.then(function (cause) {
      return Promise.reject((0, _errors2.default)(cause));
    });
  }
}
```

Perhaps better to gate the JSON parsing based on whether or not the `Content-Type` is actually `application/json`.
