### ISSUE TITLE
Add context to the parameters of the mapping function

### ISSUE THREAD

**Issue by eyalw** [heroku/react-refetch#69]
Why don't we also pass context as a second parameter to the data-mapping function?
I looks like only props are passed:
https://github.com/heroku/react-refetch/blob/master/src/components/connect.js#L156

I wish I could also access the context like so:
```javascript
DataSourceEditModal = connect((props, context) => {

  // .... check context for router or other state in it. ....

  return { ...mapping... };
}
```

**Comment by ryanbrainard** [comment]
I don't see a reason why we couldn't do this and feels like the right thing to do. There could be a limitation on the context actually being populated in the HOC, but I haven't tried. Would anyone like to test that and submit a PR?

**Comment by eyalw** [comment]
there has to be a way to specify the contextType the HOC will need access to in the mapping function.
not sure how the api should be changed.

**Comment by ryanbrainard** [comment]
Hopefully the static hoisting will take care of that.

**Comment by yairnm** [comment]
+1

**Comment by nfcampos** [comment]
I've added this in PR #86
