### ISSUE TITLE
Incompatible with stateless authentication

### ISSUE THREAD

**Issue by neezer** [heroku/react-refetch#70]
I'm using [JWT](http://jwt.io/)'s as my authentication mechanism in my SPA, persisted to `window.sessionStorage`. When I make calls to my API, I configure the request with an `Authorization: Bearer TOKEN` header that authorizes the request.

**Since API calls in `react-refetch` are defined outside the context of the component class itself, they cannot pick up changes during runtime to get the current token.**

Here's an overview of the flow:

1. User loads the application on a hard server-request; app initializes in the client, and refetch-enabled components are loaded.

  Refetch configuration on a protected route like ...

  ```es6
  // lib.js
  export const jwt = () => sessionStorage.token;
  export const authHeader = () => {
    if (jwt()) return { 'Authorization': `Bearer ${jwt()}` };
    return {};
  };

  // protected_component.js
  connect(() => ({ fetchStuff: { url: '/api/stuff', headers: authHeader() }})(Component);
  ```

  ... assign `headers: {}` since the user starts off logged-out, thus no token is present in `window.sessionStorage`.
1. User logs in. Login handler writes the returned, valid token to `window.sessionStorage`.

  ```es6
  // lib.js
  export const login = ({ token }) => {
    sessionStorage.setItem('token', token);
  };

  // login.js
  componentWillReceiveProps(nextProps) {
    if ((nextProps.postLoginResponse || {}).fulfilled) {
      login(nextProps.postLoginResponse.value);
      this.context.router.push({ pathname: '/' });
    }
  }
  ```
1. User accesses protected resource `/stuff` and refetch fails, because the API request was made with no `Authorization` header (from Step 1).

  > GET http://domain/stuff 403 (Forbidden)

--

For now, I'm working around the issue by changing:

```es6
this.context.router.push({ pathname: '/' });
```

... to ...

```es6
window.location = '/';
```

But I don't consider that an optimal solution because I have to re-initialize the entire app on successful login, which seems excessive.

Is there any other way around this? Or an alternative approach?

**Comment by eyalw** [comment]
@neezer not sure I understand the problem,
check out #9 

at the end, I suggest the package "fetch-intercept" for your use case.
It allows both interception of request and response, globally in the app,
great for intercepting all requests made by the app, and add headers to them like CSRF or JWT token.

**Comment by neezer** [comment]
@eyalw The issue is request pre-processing **at the time the request is made**, not when the class is instantiated. [@hnort's idea about "request enhancers"](https://github.com/heroku/react-refetch/issues/9#issuecomment-166420907) would work if they were executed at runtime. Similarly [his other suggestion](https://github.com/heroku/react-refetch/issues/40#issuecomment-172942228) would also work. 

> `fetch-intercept` **monkey patches** the global fetch method...

That would provide a solution, but in the form of a hack, which I'm reluctant to pursue.

**Comment by neezer** [comment]
@eyalw Here's an example failing test case of the functionality that's missing:

```es6
// connect.spec.js

it('should preprocess request object before all fetches with preflight option', (done) => {
  const props = ({
    foo: 'bar',
    baz: 42
  })

  const genRandToken = () => (Math.random().toString(36)+'00000000000000000').slice(2, 7)
  window.authToken = genRandToken()

  @connect(({ foo, baz }) => ({
    testFetch: {
      url: `/${foo}/${baz}`,
      headers: { 'Authorization': `Bearer ${window.authToken}` },
    },
  }))
  class Container extends Component {
    render() {
      return <Passthrough {...this.props} />
    }
  }

  const container = TestUtils.renderIntoDocument(
    <Container {...props} />
  )

  const newRandToken = genRandToken()
  window.authToken = newRandToken // override previous token

  setImmediate(() => {
    const stubFulfilled = TestUtils.findRenderedComponentWithType(container, Passthrough)
    expect(stubFulfilled.props.testFetch).toIncludeKeyValues({
      fulfilled: true, pending: false, refreshing: false, reason: null, rejected: false, settled: true, value: { T: 't' }
    })
    expect(stubFulfilled.props.testFetch.meta.request.headers.get('Authorization')).toEqual(`Bearer ${newRandToken}`)
    expect(stubFulfilled.props.testFetch.meta.response.status).toEqual(200)
    expect(stubFulfilled.props.testFetch.meta.response.bodyUsed).toEqual(true)

    done()
  })
})
```

This test fails with

```
React
  connect
    1) should preprocess request object before all fetches with preflight option


0 passing (200ms)
1 failing

1) React connect should preprocess request object before all fetches with preflight option:

    Uncaught Error: Expected 'Bearer 8tzo7' to equal 'Bearer 3vf92'
    + expected - actual

    -Bearer 8tzo7
    +Bearer 3vf92
```

--

I was thinking it would be easiest to provide some sort of `preflight` option, like:

```es6
@connect(({ foo, baz }) => ({
  testFetch: {
    url: `/${foo}/${baz}`,
    preflight: (request) => {
      request.headers.set('Authorization', `Bearer ${window.authToken}`)
    },
  },
}))
```

That way you could compute the value of the `Authorization` header ***at execution time*** rather than during initialization.

Does that help clarify the issue?

@ryanbrainard :money_with_wings: for your thoughts?

**Comment by neezer** [comment]
@eyalw @ryanbrainard I got a working implementation of my `preflight` idea, but I can't figure out how to make the tests simulate a change to the `window.authToken` variable... I confirmed the change does fix my app, however:

Changing [`src/components/connect.js:95`](https://github.com/heroku/react-refetch/blob/master/src/components/connect.js#L95):

```es6
function buildRequest(mapping) {
  const request = new window.Request(mapping.url, {
    method: mapping.method,
    headers: mapping.headers,
    credentials: mapping.credentials,
    redirect: mapping.redirect,
    body: mapping.body
  })

  if (Function.prototype.isPrototypeOf(mapping.preflight)) {
    mapping.preflight(request)
  }

  return request
}
```

If y'all have an idea about how to fix the test to reflect the new behavior, I'd be happy to throw up a PR for this.

--

My current test (slimmed down from the one posted above):

```es6
it('should preprocess request object before all fetches with preflight option', (done) => {
  const genRandToken = () => (Math.random().toString(36)+'00000000000000000').slice(2, 7)
  const oldRandToken = genRandToken()
  const newRandToken = genRandToken()

  // make sure the oldRandToken is the value present during initialization
  window.authToken = oldRandToken

  @connect(({ foo, baz }) => ({
    testFetch: {
      url: '/some/url',
      preflight: (request) => {
        request.headers.set('Authorization', `Bearer ${window.authToken}`)
      },
    },
  }))
  class Container extends Component {
    render() {
      return <Passthrough {...this.props} />
    }
  }

  const container = TestUtils.renderIntoDocument(
    <Container />
  )

  // after initialization, override with the newRandToken
  window.authToken = newRandToken

  setImmediate(() => {
    const stubFulfilled = TestUtils.findRenderedComponentWithType(container, Passthrough)
    expect(stubFulfilled.props.testFetch).toIncludeKeyValues({
      fulfilled: true, pending: false, refreshing: false, reason: null, rejected: false, settled: true, value: { T: 't' }
    })
    expect(stubFulfilled.props.testFetch.meta.request.headers.get('Authorization')).toEqual(`Bearer ${newRandToken}`)
    expect(stubFulfilled.props.testFetch.meta.response.status).toEqual(200)
    expect(stubFulfilled.props.testFetch.meta.response.bodyUsed).toEqual(true)

    done()
  })
})
```

I get the same failure as before with or without the change, but in my manual testing with a live browser window, the change works as expected. I suspect it's something to do with my `window.authToken` update not happening correctly with `setImmediate`, but every permutation I've tried has failed.

**Comment by neezer** [comment]
Nm, I've determined that there is a bug in my code and this is not actually an issue. Sorry for the issue spam!
