### ISSUE TITLE
Allow PromiseState.all(aFetch, bFetch) in addition to PromiseState.all([aFetch, bFetch])

### ISSUE THREAD

**Issue by nfcampos** [heroku/react-refetch#78]
Hi,

Would you be opposed to changing the signature of PromiseState.all() and .race() so that if more than 1 argument is provided all are collected in an array? It'd make for more natural code when using those two methods.

Thanks for making react-refetch, it's great!

Thanks,
Nuno

**Comment by nfcampos** [comment]
also, even though the api documentation mentions these two functions taking as an argument an `iterable`, the current implementations only allow for providing arrays, since they then call Array.prototype methods on it. A simple fix would be to add a line at the begging of each doing
`iterable = Array.from(iterable)`

**Comment by ryanbrainard** [comment]
I'm not completely opposed to it, but wanted these methods to mirror their `Promise` counterparts. It also provides nice symmetry with array spread syntax:

    const [a, b] = PromiseState.all([aFetch, bFetch])

> these two functions taking as an argument an iterable but the current implementations only allow for providing arrays

Good catch! That's what I get for copying the `Promise` API doc :)

**Comment by ryanbrainard** [comment]
Broke out the iterable bug in https://github.com/heroku/react-refetch/issues/79.

Going to mark this as "discussion" if other people have thoughts, but at this point, I'm slightly opposed to allowing separate parameters.

**Comment by nfcampos** [comment]
yes, the parity with Promise.all() is a good point, maybe it's not worth it

**Comment by ryanbrainard** [comment]
> maybe it's not worth it

Closing this for now. Re-open if there's still a reason to do this.
