### ISSUE TITLE
Custom Request Pre-Processing

### ISSUE THREAD

**Issue by thomasloh** [heroku/react-refetch#9]
for example, ability to specify default header(s) to be added to all requests

**Comment by ryanbrainard** [comment]
I have considered something like this, and not a bad idea, but so far, I've done things like this, which has worked in the limited places I have needed it:

```
export default connect(({ params: { userId }, location: pathname }) => {
  const common = (urls) => Object.keys(urls).reduce((reqs, p) => {
    reqs[p] = {
      url: urls[p],
      comparison: pathname,
      refreshing: true,
      headers: {
        'X-Custom-Header': 'true'
      }
    }
    return reqs
  }, {})

  return common({
    userFetch: `/proxy/users/${userId}`,
    likesFetch:  `/proxy/likes/${userId}`,
  })
})(Profile)
```

If we did something like this, I'm thinking some kind of similar function set in `options` that would be run on every request after it has been coerced into a canonical request (i.e. in the full object form, not just a URL), but before `fetch()` is called. Is that what you were thinking?

**Comment by thomasloh** [comment]
@ryanbrainard yeah exactly. A way to specify common metadata to be coerced into the final canonical request, and should allow overrides as well.

The bigger question is probably how/where to do it, because the metadata should only be specified in one place, upfront somewhere. And then is used by all connect(), or selectively via decorators

**Comment by ryanbrainard** [comment]
@thomasloh I'm hesitant to add any global options, but this could be a common option that's passed into every `connect()`. It would be just one extra line, so not too much boilerplate and would avoid global/singleton messiness. Something like this:

```.jsx
export default connect(({ params: { userId }, location: pathname }) => {
  return {
    userFetch: `/proxy/users/${userId}`,
    likesFetch:  `/proxy/likes/${userId}`,
  }
}, requestPreprocessor: myCommonRequestPreprocessor)(Profile)
```

where `myCommonRequestPreprocessor` is a function similar to the `common()` one I showed before but defined in a separate file so it can be shared. I'm thinking the function would probably take `(requests, props)` and return `requests`. How does that sound? Also, open to a better, shorter name than `requestPreprocessor`. 

Another way to possibly do it is instead of making it a pre-processor, it would be letting applications overrides the defaults used in [`buildRequest()`](https://github.com/heroku/react-refetch/blob/019a17057d7af6c22e4c9e160e77d08a11ec41c0/src/components/connect.js#L65-L76).

Also to consider: the order of exactly when this happens. Should it be before, after, or completely replace [`buildRequest()`](https://github.com/heroku/react-refetch/blob/019a17057d7af6c22e4c9e160e77d08a11ec41c0/src/components/connect.js#L65-L76).

**Comment by thomasloh** [comment]
@ryanbrainard oh yeah no definitely don't want to maintain any state there! I should rephrase, it should be defined once somewhere, like you suggested, in a separate module/file, which can then be used by interested `connect()`.

Personally I like the idea of preprocessors, because it behaves like middleware and allow composition. Something like,

```js
// requestPreprocessor.js

const compose = (...fns) => (reqs, props) => fns.reduce((finalReqs, fn) =>  fn(finalReqs, props), reqs);

function addAuthorizationHeader(reqs, props) {
}

function addComparison(reqs, props) {
}

export default compose(
  addAuthorizationHeader,
  addComparison
  ...
)
```

Calling it just `preprocessor` sounds good to me, so like
```js
import refetchPreprocessor from "/common/refetch-preprocessor" // naming of this is in userland of course

connect(() => {...}, preprocessor: refetchPreprocessor)
```

**Comment by hnordt** [comment]
@ryanbrainard 

I don't think we need global options. What do you think about a different approach:

## refetch-preprocessor.js

```js
const refetchPreprocessor = urls => Object.keys(urls).reduce((reqs, p) => {
    reqs[p] = {
      url: `http://foo.com/api/${urls[p]}`,
      headers: {
        foo: 'bar'
      }
    }
    return reqs;
  }, {});

export default refetchPreprocessor;
```

## Usage

```js
import refetchPreprocessor from './refetchPreprocessor.js';

export default connect(({ params: { userId } }) => {
  return refetchPreprocessor({
    userFetch: `/proxy/users/${userId}`,
    likesFetch:  `/proxy/likes/${userId}`,
  })
})(Profile);
```

**Comment by hnordt** [comment]
I liked your approach, maybe we can support something like `enhancers`.

## Usage

```js
import enhancers from '/refetch-enhancers.js';

export default connect(props => ({ foo: 'bar' }), enhancers)`;
```

## refetch-enhancers.js

```js
const requestEnhancer = request => ({
  url: `http://foo.com/api/${request.url}`,
  headers: { // Note: headers is merged instead replaced
    'foo': 'bar'
  }
});

const responseEnhancer = (request, response) => {
  return Promise((resolve, reject) => {
    if (request.dataType === 'csv') {
      myCSVParser(response.body).then(data => resolve(Object.assign({}, response, { body: data }))).catch(error => reject(new Error(error));
    }
    resolve(response.body);
  });
};

export default { requestEnhancer, responseEnhancer };
```

## New buildRequest

```js
  function buildRequest(mapping, enhancer) {
    mapping = enhancer ? enhancer(mapping) : mapping;
    return new window.Request(mapping.url, {
      method: mapping.method || 'GET',
      headers: Object.assign({
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      }, mapping.headers),
      credentials: mapping.credentials || 'same-origin',
      redirect: mapping.redirect || 'follow',
      body: mapping.body
    })
  }
```

## new handleResponse

```js
  function handleResponse(response, enhancer) {
    if (enhancer) {
      return enhancer; // TODO: handle errors | TODO²: promises is a bad idea?
    }
    const json = response.json() // TODO: support other response types
    if (response.status >= 200 && response.status < 300) { // TODO: support custom acceptable statuses
      return json
    } else {
      return json.then((errorJson) => {
        const { id, error, message } = errorJson
        if (error) {
          throw new Error(error, id)
        } else if (message) {
          throw new Error(message, id)
        } else {
          throw new Error(errorJson)
        }
      })
    }
  }
```

**Comment by LucaColonnello** [comment]
@hnordt Great Idea!! I'm waiting this ti use this lib in production! Are you making some of these changhes?

**Comment by apsaros** [comment]
@hnordt +1
and great work with the lib @ryanbrainard :)

**Comment by hnordt** [comment]
@ryanbrainard my suggestion on https://github.com/heroku/react-refetch/issues/40#issuecomment-172942228 can handle this.

**Comment by eyalw** [comment]
May I suggest [fetch-intercept](https://github.com/werk85/fetch-intercept)?
It allows both interception of request and response, globally in the app,
great for value adapters, and header settings (like csrf).

**Comment by ryanbrainard** [comment]
[v1.0.0-beta.0](https://github.com/heroku/react-refetch/releases/tag/v1.0.0-beta.0) has the ability to change the `buildRequest`, `fetch`, and `handle Response` implementations, which should open up a lot of possibilities here. These features are probably a little too low level for everyday pre-processing; however, I want people to kick the tires on them and see what can possibly be built on top of them. I'm going to close this issue now so that we can re-frame remaining enhancements in this new context by opening new issues.

**Comment by LucaColonnello** [comment]
Good work guys!

Il lunedì 28 marzo 2016, Ryan Brainard <notifications@github.com> ha
scritto:

> v1.0.0-beta.0
> <https://github.com/heroku/react-refetch/releases/tag/v1.0.0-beta.0> has
> the ability to change the buildRequest, fetch, and handle Response
> implementations, which should open up a lot of possibilities here. These
> features are probably a little too low level for everyday pre-processing;
> however, I want people to kick the tires on them and see what can possibly
> be built on top of them. I'm going to close this issue now so that we can
> re-frame remaining enhancements in this new context by opening new issues.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/react-refetch/issues/9#issuecomment-202268620>
>


-- 
Luca Colonnello
+39 345 8948718
luca.colonnello91@gmail.com
