### ISSUE TITLE
PromiseState and any other kind of promised props

### ISSUE THREAD

**Issue by nfcampos** [heroku/react-refetch#92]
So I've found a kind of sideways use for the ideas of PromiseState and connect (as a HOC that computes additional async props from your regular props). Components that need to compute props asynchronously derived from the other props need most of the ideas behind react-refetch (the props need to be represented as something that can be fulfilled, rejected, pending; it needs figure out whether to recompute when props change). In a way it's a lower-level primitive on top of which react-refetch is built. Do you think it belongs in react-refetch in any way?

I'm using it like this:
```js
export default withPromisedProps({
  table: {
    dependentProps: ['file'], // every time one of these props changes table is recomputed
    then: ({file}) => promisedFileReader(file).readAsText().then(csvParse)
  }
})(CsvTable)
```

Not sure if this is relevant to anyone, feel free to close this issue :)

**Comment by ryanbrainard** [comment]
I need to think about this a bit more, but some initial thoughts:
 - can `dependentProps` be worked into `comparison` and/or `value` somehow? If possible, I'd like to have this based on identity requests. Perhaps `value` could take a `Promise` and do things like this.
 - I've considered breaking out `PromiseState` into a separate npm module. Perhaps that would help *if* we a separate module for this kind of thing.

**Comment by nfcampos** [comment]
- `value` optionally taking a promise is a great idea, sounds like a very natural extension of the current API (and it looks like it'd be pretty trivial to implement, just change this line https://github.com/heroku/react-refetch/blob/master/src/components/connect.js#L345 to `return Promise.resolve(value).then(onFulfillment(meta), onRejection(meta))`
- as for `dependentProps`, it is kind of a specific implementation of a `comparison` function (called with (prevProps, nextProps) as arguments), if we had such a thing. But being able to specify comparison as an array of props to be shallowly compared actually sounds like something that would be useful for regular requests as well, what do you think? (btw, this api of dependentProps as an array of props to be compared was inspired by this https://github.com/acdlite/recompose/blob/master/src/packages/recompose/mapPropsOnChange.js)
- today I also considered whether PromiseState should be its own module, but honestly as long as you export it in react-refetch there's no practical difference at all, I had no trouble implementing this today importing PromiseState from react refetch

**Comment by nfcampos** [comment]
#93 does the most significant part of this, so I'll close this issue
