### ISSUE TITLE
add static version of PromiseState#_mapFlatMapValue ?

### ISSUE THREAD

**Issue by nfcampos** [heroku/react-refetch#97]
That method is useful when building components that receive a prop that may or may not be a PromiseState.

eg.
```js
const Comp = ({table}) => {
  table = table instanceof PromiseState ? table : PromiseState.resolve(table)
  return (
    <div>
      {table.fulfilled && <span>{table.value.length}</span>}
    <div>
  )
}
```

(It should probably get a name like `PromiseState.ensure()`, mapFlatMapValue is kind of cryptic)

Sounds like a useful addition?

**Comment by ryanbrainard** [comment]
Instead of exposing it, it seems like `PromiseState.resolve` should just call flatten the value implicitly. This would mirror what `Promise.resolve` does. Ditto for similar methods.

**Comment by ryanbrainard** [comment]
Thinking about this a little more, `PromiseState.resolve` should probably do as I explained above, but only for fulfilled `PromiseState`s. It would be weird to call `PromiseState.resolve(PromiseState.rejected('x'))` and expect it to actually be fulfilled -- instead, I think this should throw an error. This does open up room for your original ask. I'll open a PR shortly.

**Comment by nfcampos** [comment]
To be consistent with `Promise.resolve` I think I actually agree with your first comment, since `Promise.resolve(new Promise((resolve, reject) => reject()))` is a rejected promise it sounds like PromiseState.resolve() should do
```
if (value instanceof PromiseState)
  return value
else
  return new PromiseState({
      fulfilled: true,
      value: value,
      meta: meta
    })
```

**Comment by ryanbrainard** [comment]
You're right. I tested out `Promise.resolve(new Promise((resolve, reject) => reject()))` when working on #105, but for some reason I remember it nesting the promises. It must have been late, because I just did it again and it works as you explained. I'll change #105 to just return the `PromiseState` and get rid of `#cast` since I don't think there's much value in that anymore.
